Source/w3schools_WEB/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using System;
using w3schools_WEB.ApiCaller;
using w3schools_WEB.Helpers;

namespace w3schools_WEB.Controllers
{
    public class AdminController : Controller
    {
        private readonly Session sess;
        public AdminController(IOptionsSnapshot<ApiUrl> app /*,IOptionsSnapshot<AuthenInfo> authen*/)
        {
            ApplicationSettings.WebApiUrl = app.Value.WebApiBaseUrl;
            sess = new Session();
        }
        public IActionResult Index()
        {
            var curUser = sess.GetUserInfo(HttpContext);
            if (curUser.Role == "Administrator")
                return View();
            else if (!String.IsNullOrEmpty(curUser.Email))
                return RedirectToAction("Index", "Home");
            else
                return RedirectToAction("Login", "Auth");
        }
    }
}

Source/w3schools_WEB/Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using w3schools_API.Models;
using w3schools_WEB.ApiCaller;
using w3schools_WEB.Helpers;

namespace w3schools_WEB.Controllers
{
    public class AuthController : Controller
    {
        public IActionResult Login()
        {
            return View();
        }
        public IActionResult Signup()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> LoginMethod(Users data)
        {
            if (data != null)
            {
                var rt = new DataResults<UserInfo>();                
                if (String.IsNullOrEmpty(data.Email))
                {
                    rt.Message += "Email is required!";
                }
                else
                {
                    data.Email = data.Email.ToLower().Trim();
                    string emailRegex = @"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}" +
                                        @"\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\" +
                                        @".)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$";
                    Regex re = new Regex(emailRegex);
                    if (!re.IsMatch(data.Email))                    
                        rt.Message += "Email is not valid!";                    
                }
                if (String.IsNullOrEmpty(data.PassWord))
                {
                    rt.Message += "Password is required!";
                }               
                if (!String.IsNullOrEmpty(rt.Message))
                    return Ok(rt);
            }

            var rs = await ApiClientFactory.Instance.checkLogin(data);

            if (rs.Status == 1)
            {
                var session = HttpContext.Session;

                var obj = new UserInfo();
                obj = rs.Data;

                var memoryCache = new Session();
                memoryCache.AddSection(session, obj);
            }
            return Ok(rs);
        }        
        public  IActionResult Signout()
        {
            var sess = new Session();
            var curUser = sess.GetUserInfo(HttpContext);

            if (curUser != null)
            {                
                var session = HttpContext.Session;
                sess.ClearSection(session);                
            }
            return View("Login");
        }

        [HttpGet]
        public IActionResult SignoutWithAjax()
        {
            var rt = new DataResults<int>();
            var sess = new Session();
            var curUser = sess.GetUserInfo(HttpContext);

            if (curUser != null)
            {
                var session = HttpContext.Session;
                sess.ClearSection(session);
                rt.Message = "Successfuly";
                rt.Status = 1;
            }
            else
            {
                rt.Message = "Failed";
                rt.Status = -1;
            }
            return Ok(rt);
        }

        [HttpPost]
        public async Task<IActionResult> SignupMethod(SingupModel data)
        {
            if (data != null)
            {
                var rt = new DataResults<UserInfo>();
                if (String.IsNullOrEmpty(data.UserName))
                {
                    rt.Message = "Username is required!";
                }
                if (String.IsNullOrEmpty(data.Email))
                {
                    rt.Message += "Email is required!";
                }
                else
                {
                    data.Email = data.Email.ToLower().Trim();
                    string emailRegex = @"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}" +
                                        @"\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\" +
                                        @".)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$";
                    Regex re = new Regex(emailRegex);
                    if (!re.IsMatch(data.Email))
                    {
                        rt.Message += "Email is not valid!";
                    }
                }
                if(String.IsNullOrEmpty(data.PassWord) || String.IsNullOrEmpty(data.RePassWord))
                {
                    rt.Message += "Password and Re-enter Password is required!";
                }
                else if(data.PassWord != data.RePassWord) {
                    rt.Message += "Re-enter password is not match!";
                }
                else
                {
                    data.PassWord = data.PassWord.Trim();
                    var hasNumber = new Regex(@"[0-9]+");
                    var hasUpperChar = new Regex(@"[A-Z]+");
                    var hasMinimum8Chars = new Regex(@".{8,}");

                    var isValidated = hasNumber.IsMatch(data.PassWord) && hasUpperChar.IsMatch(data.PassWord) && hasMinimum8Chars.IsMatch(data.PassWord);
                    if (!isValidated)
                    {
                        rt.Message += "Password must contain numbers, uppercase letters and be at least 8 characters long!";
                    }
                }
                if (!String.IsNullOrEmpty(rt.Message))
                    return Ok(rt);
            }
            data.RoleId = 2;
            var rs = await ApiClientFactory.Instance.signup(data);

            if (rs.Status == 1)
            {
                var session = HttpContext.Session;

                var obj = new UserInfo();
                obj = rs.Data;

                var memoryCache = new Session();
                memoryCache.AddSection(session, obj);
            }
            return Ok(rs);
        }
    }
}

Source/w3schools_WEB/Controllers/RolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using w3schools_API.Models;
using w3schools_WEB.ApiCaller;
using w3schools_WEB.Helpers;
using w3schools_WEB.Models;

namespace w3schools_WEB.Controllers
{
    public class RolesController : Controller
    {
        private readonly Session sess;
        public RolesController(IOptionsSnapshot<ApiUrl> app)
        {
            ApplicationSettings.WebApiUrl = app.Value.WebApiBaseUrl;
            sess = new Session();
        }
        public IActionResult Index()
        {
            var curUser = sess.GetUserInfo(HttpContext);
            if (curUser.Role == "Administrator")
                return View();
            else if (!String.IsNullOrEmpty(curUser.Email))
                return RedirectToAction("Index", "Home");
            else
                return RedirectToAction("Login", "Auth");
        }        
        [HttpGet]
        public async Task<IActionResult> GetListRoles()
        {
            var curUser = sess.GetUserInfo(HttpContext);

            curUser.Token = await ApiClientFactory.Instance.RefeshToken(curUser);

            sess.SetUserInfo(curUser, HttpContext);

            var returns = await ApiClientFactory.Instance.getListRole(curUser.Token);
            return Json(returns);           
        }

        [HttpPost]
        public async Task<IActionResult> UpdateBatchRoles([FromBody] IEnumerable<UpdateBatchData<Roles>> data)
        {
            var curUser = sess.GetUserInfo(HttpContext);

            if (curUser != null)
            {
                curUser.Token = await ApiClientFactory.Instance.RefeshToken(curUser);

                sess.SetUserInfo(curUser, HttpContext);
                var result = await ApiClientFactory.Instance.updateBatchRole(data, curUser.UserName,curUser.Token);
                return Json(result);
            }
            return null;            
        }
    }
}

Source/w3schools_WEB/Controllers/UsersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using w3schools_API.Models;
using w3schools_WEB.ApiCaller;
using w3schools_WEB.Helpers;
using w3schools_WEB.Models;

namespace w3schools_WEB.Controllers
{
    public class UsersController : Controller
    {
        private readonly Session sess;
        public UsersController(IOptionsSnapshot<ApiUrl> app)
        {
            ApplicationSettings.WebApiUrl = app.Value.WebApiBaseUrl;
            sess = new Session();
        }
        public IActionResult Index()
        {
            var curUser = sess.GetUserInfo(HttpContext);
            if (curUser.Role == "Administrator")
                return View();
            else if (!String.IsNullOrEmpty(curUser.Email))
                return RedirectToAction("Index", "Home");
            else
                return RedirectToAction("Login", "Auth");
        }
        [HttpGet]
        public async Task<IActionResult> GetListUsers()
        {
            var curUser = sess.GetUserInfo(HttpContext);

            if (curUser != null)
            {
                curUser.Token = await ApiClientFactory.Instance.RefeshToken(curUser);

                sess.SetUserInfo(curUser, HttpContext);
               var returns = await ApiClientFactory.Instance.getListUser(curUser.Token);
                return Json(returns);
            }
            return null;
        }
        [HttpGet]
        public async Task<IActionResult> DeleteUsers(int id = -1)
        {
            if (ModelState.IsValid)
            {
                var curUser = sess.GetUserInfo(HttpContext);

                if (curUser != null)
                {
                    curUser.Token = await ApiClientFactory.Instance.RefeshToken(curUser);

                    sess.SetUserInfo(curUser, HttpContext);
                    var result = new DataResults<int>();
                    if (id != -1)
                    {
                        result = await ApiClientFactory.Instance.deleteUser(id, curUser.Token);
                        return Json(result);
                    }
                }
                return null;
            }
            return BadRequest("Request error");
        }
        [HttpPost]
        public async Task<IActionResult> InsertUsers([FromBody]Users data)
        {

            if (ModelState.IsValid)
            {
                var curUser = sess.GetUserInfo(HttpContext);

                if (curUser != null)
                {
                    curUser.Token = await ApiClientFactory.Instance.RefeshToken(curUser);

                    sess.SetUserInfo(curUser, HttpContext);
                    var result = new DataResults<Users>();
                    result = await ApiClientFactory.Instance.insertUser(data, curUser.UserName, curUser.Token);
                    return Json(result);
                }
                return null;  
            }
            return BadRequest("Request error");
        }
    }
}

Source/w3schools_WEB/Views/Shared/Admin_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewData["Title"] W3Schools Admin Page </title>
    <link rel="icon" href="~/image/favicon.ico" />
    <!--bootstrap, jquery w3schools-->
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous" />
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500&family=Source+Sans+Pro:ital,wght@0,300;0,400;0,600;0,700;0,900;1,900&display=swap" rel="stylesheet">
    <!--devextreme-->
    <link rel="stylesheet" type="text/css" href="https://cdn3.devexpress.com/jslib/21.1.6/css/dx.common.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn3.devexpress.com/jslib/21.1.6/css/dx.light.css" />
    <!-- template CSS -->
    <link rel="stylesheet" href="~/admin/dist/css/adminlte.min.css">
    <link href="~/css/site.css" rel="stylesheet" />
    <link href="~/css/base.css" rel="stylesheet" />

    <!--end template-->
    <!--font-awesome-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" />
    <!--codemirror lib-->
    <link href="~/lib/codemirror/lib/codemirror.css" rel="stylesheet" />
    <link href="~/lib/codemirror/theme/3024-day.css" rel="stylesheet" />

</head>
<body class="hold-transition sidebar-mini">
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="@Url.Action("Index","Admin")" class="nav-link">Home</a>
                </li>                
            </ul>

            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                <!-- User info -->
                <li class="nav-item dropdown">
                    <a class="nav-link" data-toggle="dropdown" href="#">
                        <i class="fas fa-user-circle"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                        <a href="@Url.Action("Signout","Auth")" class="dropdown-item" id="signout">
                            <i class="fas fa-sign-out-alt mt-2 mr-2"></i>Sign out                            
                        </a>
                        @*<div class="dropdown-divider"></div>*@
                    </div>
                </li>

            </ul>
        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <div class="text-center">
                <a href="@Url.Action("Index","Home")" class="brand-link"><img id="logo" src="~/image/favicon.ico" /></a>
            </div>
            <!-- Sidebar -->
            <div class="sidebar">
                
                <!-- Sidebar Menu -->
                <nav class="mt-2 " id="sidebar">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
                        with font-awesome or any other icon font library -->
                        <li class="nav-item"><a href="@Url.Action("Index","Lesson")" class="nav-link text-light"><i class="nav-icon fas fa-book-reader"></i><span>Lesson</span></a></li>
                        <li class="nav-item"><a href="@Url.Action("Index","LessonContents")" class="nav-link text-light"><i class="nav-icon fas fa-file-code"></i><span>Lesson Content</span></a></li>
                        <li class="nav-item"><a href="@Url.Action("Index","LessonCategories")" class="nav-link text-light"><i class="nav-icon fas fa-layer-group"></i><span>Lesson Category</span></a></li>
                        <li class="nav-item"><a href="@Url.Action("Index","ContentType")" class="nav-link text-light"><i class="nav-icon fas fa-file-alt"></i><span>Content Type</span></a></li>
                        <li class="nav-item"><a href="@Url.Action("Index","Users")" class="nav-link text-light"><i class="nav-icon fas fa-user"></i><span>User</span></a></li>
                        <li class="nav-item"><a href="@Url.Action("Index","Roles")" class="nav-link text-light"><i class="nav-icon fas fa-user-tag"></i><span>Role</span></a></li>
                        <li class="nav-item"><a href="@Url.Action("Index","Example")" class="nav-link text-light"><i class="nav-icon fas fa-code"></i><span>Example Code</span></a></li>
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="container-fluid">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb my-0 ms-2">
                        <li class="breadcrumb-item"><span>Home</span></li>
                        <li class="breadcrumb-item active"><span></span></li>                        
                    </ol>
                </nav>
            </div>
            <!-- /.content-header -->
            <!-- Main content -->
            <div class="content">
                <div class="w-100">
                    <!-- Javascript -->
                    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
                    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
                    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
                    <script src="https://unpkg.com/devextreme-quill/dist/dx-quill.min.js"></script>
                    <script src="https://cdn3.devexpress.com/jslib/21.1.6/js/dx.all.js"></script>
                    <script src="~/lib/codemirror/lib/codemirror.js"></script>
                    <script src="~/lib/codemirror/addon/edit/closebrackets.js"></script>
                    <script src="~/lib/codemirror/addon/edit/closetag.js"></script>
                    <script src="~/lib/codemirror/addon/runmode/colorize.js"></script>
                    @*<script src="~/lib/codemirroraddon/hint/show-hint.js"></script>
                    <script src="~/lib/codemirror/addon/hint/xml-hint.js"></script>
                    <script src="~/lib/codemirror/addon/hint/html-hint.js"></script>*@
                    <script src="~/lib/codemirror/mode/xml/xml.js"></script>
                    <script src="~/lib/codemirror/mode/javascript/javascript.js"></script>
                    <script src="~/lib/codemirror/mode/css/css.js"></script>
                    <script src="~/lib/codemirror/mode/htmlmixed/htmlmixed.js"></script>
                    <!-- live code js-->
                    <script src="~/js/editor.js"></script>
                    <script src="~/admin/dist/js/adminlte.min.js"></script>
                    <div class="pl-3 pr-3">@RenderBody()</div>                    
                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
        <!-- Main Footer -->
        <footer class="main-footer text-black-50 text-center">
            <small>Copyright &copy; 2021 <a class="text-info" href="#">W3Schools  </a> . All rights reserved.   </small>                        
        </footer>
    </div>
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Source/w3schools_WEB/Views/Shared/_AuthLayout.cshtml
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>@ViewData["Title"] </title>
    <link rel="icon" href="~/image/favicon.ico" />
    <!--bootstrap, jquery w3schools-->
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous" />
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500&family=Source+Sans+Pro:ital,wght@0,300;0,400;0,600;0,700;0,900;1,900&display=swap" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <!--front-end-->
    <link href="~/css/base.css" rel="stylesheet" />
    <link href="~/css/reset.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />
    <script src="~/js/site.js"></script>
</head>
<body>
    @RenderBody()
</body>

Source/w3schools_WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>@ViewData["Title"] W3Schools Online Web Tutorials</title>
    <link rel="icon" href="~/image/favicon.ico" />
    <!--bootstrap, jquery w3schools-->
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <!--devextreme-->
    <link rel="stylesheet" type="text/css" href="https://cdn3.devexpress.com/jslib/21.1.6/css/dx.common.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn3.devexpress.com/jslib/21.1.6/css/dx.light.css" />
    <script src="https://unpkg.com/devextreme-quill/dist/dx-quill.min.js"></script>
    <script src="https://cdn3.devexpress.com/jslib/21.1.6/js/dx.all.js"></script>
    <!--front-end-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500&family=Source+Sans+Pro:ital,wght@0,300;0,400;0,600;0,700;0,900;1,900&display=swap" rel="stylesheet">
    <link href="~/css/base.css" rel="stylesheet" />
    <link href="~/css/reset.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />
    <script src="~/js/site.js"></script>
    <!-- live code js-->
    <script src="~/js/editor.js"></script>
    <!--font-awesome-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" />
    <!--codemirror lib-->
    <script src="~/lib/codemirror/lib/codemirror.js"></script>
    <link href="~/lib/codemirror/lib/codemirror.css" rel="stylesheet" />
    <link href="~/lib/codemirror/theme/3024-day.css" rel="stylesheet" />
    <script src="~/lib/codemirror/addon/edit/closebrackets.js"></script>
    <script src="~/lib/codemirror/addon/edit/closetag.js"></script>
    <script src="~/lib/codemirror/addon/runmode/colorize.js"></script>
    @*<script src="~/lib/codemirroraddon/hint/show-hint.js"></script>
        <script src="~/lib/codemirror/addon/hint/xml-hint.js"></script>
        <script src="~/lib/codemirror/addon/hint/html-hint.js"></script>*@
    <script src="~/lib/codemirror/mode/xml/xml.js"></script>
    <script src="~/lib/codemirror/mode/javascript/javascript.js"></script>
    <script src="~/lib/codemirror/mode/css/css.js"></script>
    <script src="~/lib/codemirror/mode/htmlmixed/htmlmixed.js"></script>



    @*<script src="~/lib/codemirror/addon/scroll/simplescrollbars.js"></script>*@
</head>
<body>
    <div class="app">
        <header class="header">
            <nav class="navbar navbar-expand-md navbar-light bg-light sticky-top">
                <div class="container-fluid">
                    <a class="navbar-branch" href="#">
                        <img src="~/image/favicon.ico" height="50" />
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="nav-menu collapse navbar-collapse" id="navbarResponsive">
                        <ul class="nav justify-content-center">
                            <li class="nav-item">
                                <a class="nav-link active" href="#">Giới thiệu</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Nâng cao</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Responsive</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Lưới</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Sass</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Ví dụ</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Tham chiếu</a>
                            </li>
                        </ul>
                    </div>
                    <div id="acc">
                        <div class="account">
                            <div class="login">
                                <a href="@Url.Action("Login","Auth")">Đăng Nhập</a>
                            </div>
                            <div class="register">
                                <a href="@Url.Action("Signup","Auth")">Đăng Ký</a>
                            </div>
                        </div>
                    </div>
    <form class="form-inline" action="/action_page.php">
        <input class="search-input form-control mr-sm-2" type="text" placeholder="Tìm kiếm" />
        <button class="btn btn-success btn-search" type="submit">Tìm kiếm</button>
    </form>
</div>
            </nav>
        </header>
        <div class="main">
            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-xl-2">
                            <div class="sidebar">
                                <ul class="sidebar-list">
                                    <li class="sidebar-item active"><a href="" class="sidebar-link">CSS Home</a></li>                                    
                                </ul>
                            </div>
                        </div>
                        <div class="col-xl-10">
                            <div class="main-content">
                                <h1 class="content-title"></h1>
                                <div class="btn-prevnext">
                                    <a href="" class="btn-link btn-prev">
                                        <i class="fas fa-chevron-left"></i>
                                        Trước
                                    </a>
                                    <a href="" class="btn-link btn-next">
                                        Kế tiếp
                                        <i class="fas fa-chevron-right"></i>
                                    </a>
                                </div>
                                <!--body here-->
                                <div id="content-body" class="content-body">
                                    @RenderBody()
                                </div>
                                <div class="btn-prevnext">
                                    <a href="" class="btn-link btn-prev">
                                        <i class="fas fa-chevron-left"></i>
                                        Trước   
                                    </a>
                                    <a href="" class="btn-link btn-next">
                                        Kế tiếp
                                        <i class="fas fa-chevron-right"></i>
                                    </a>
                                </div>
                                <hr />
                                <footer class="footer">
                                    <p class="w3-decription">
                                        W3Schools được tối ưu hóa cho việc học tập và đào tạo. Các ví dụ có thể được đơn giản hóa để cải thiện việc đọc và học. Các hướng dẫn, tài liệu tham khảo và ví dụ được xem xét liên tục để tránh sai sót, nhưng chúng tôi không thể đảm bảo tính đúng đắn hoàn toàn của tất cả nội dung. Trong khi sử dụng W3Schools, bạn đồng ý đã đọc và chấp nhận các điều khoản sử dụng, cookie và chính sách bảo mật của chúng tôi.  
                                    </p>
                                    <p class="w3-copyright">
                                        Bản quyền 1999-2021 bởi Refsnes Data. Đã đăng ký Bản quyền. <br />
                                        W3Schools được cung cấp bởi W3.CSS .
                                    </p>
                                    <a href="" class="logo-link"><img src="~/image/favicon.ico" alt="" /></a>
                                </footer>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>