Source/w3schools_WEB/Controllers/ContentTypeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using w3schools_API.Models;
using w3schools_WEB.ApiCaller;
using w3schools_WEB.Helpers;
using w3schools_WEB.Models;

namespace w3schools_WEB.Controllers
{
    public class ContentTypeController : Controller
    {
        private readonly Session sess;
        public ContentTypeController(IOptionsSnapshot<ApiUrl> app)
        {
            ApplicationSettings.WebApiUrl = app.Value.WebApiBaseUrl;
            sess = new Session();
        }
        public IActionResult Index()
        {
            var curUser = sess.GetUserInfo(HttpContext);
            if (curUser.Role == "Administrator")
                return View();
            else if (!String.IsNullOrEmpty(curUser.Email))
                return RedirectToAction("Index", "Home");
            else
                return RedirectToAction("Login", "Auth");
        }
        [HttpGet]
        public async Task<IActionResult> GetListContentType()
        {
            var curUser = sess.GetUserInfo(HttpContext);

            if (curUser != null)
            {
                curUser.Token = await ApiClientFactory.Instance.RefeshToken(curUser);

                sess.SetUserInfo(curUser, HttpContext);
                var returns = await ApiClientFactory.Instance.getListContentType(curUser.Token);
                return Json(returns);
            }
            return BadRequest("Request error");
        }

        [HttpPost]
        public async Task<IActionResult> UpdateBatchContentType([FromBody] IEnumerable<UpdateBatchData<ContentTypes>> data)
        {
            var curUser = sess.GetUserInfo(HttpContext);

            if (curUser != null)
            {
                curUser.Token = await ApiClientFactory.Instance.RefeshToken(curUser);

                sess.SetUserInfo(curUser, HttpContext);
                var result = await ApiClientFactory.Instance.updateBatchContentType(data, curUser.UserName, curUser.Token);
                return Json(result);
            }
            return BadRequest("Request error");  
        }
    }
}

Source/w3schools_WEB/Controllers/LessonContentsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using w3schools.Models;
using w3schools_API.Models;
using w3schools_WEB.ApiCaller;
using w3schools_WEB.Helpers;
using w3schools_WEB.Models;

namespace w3schools.Controllers
{
    public class LessonContentsController : Controller
    {
        private readonly Session sess;
        public LessonContentsController(IOptionsSnapshot<ApiUrl> app /*,IOptionsSnapshot<AuthenInfo> authen*/)
        {
            ApplicationSettings.WebApiUrl = app.Value.WebApiBaseUrl;
            sess = new Session();
        }

        public IActionResult Index(string contentType)
        {
            var curUser = sess.GetUserInfo(HttpContext);
            if (curUser.Role == "Administrator")
                return View();
            else if (!String.IsNullOrEmpty(curUser.Email))
                return RedirectToAction("Index", "Home");
            else 
                return RedirectToAction("Login", "Auth");
        }

        public async Task<IActionResult> AddEditLessonContentsView(string method,int id = -1,int order=-1)
        {
            if (ModelState.IsValid)
            {
                var curUser = sess.GetUserInfo(HttpContext);

                if (curUser != null)
                {
                    curUser.Token = await ApiClientFactory.Instance.RefeshToken(curUser);

                    sess.SetUserInfo(curUser, HttpContext);
                    var model = new LessonContents();
                    if (id != -1)
                    {
                        model = await ApiClientFactory.Instance.GetLessonContentById(id, curUser.Token);                        
                    }
                    ViewBag.Method = method;
                    ViewBag.RowOrder = order;
                    return View(model);
                }                               
            }
            return BadRequest("Request error");
        }

        [HttpGet]
        public async Task<IActionResult> GetListLessContent(bool filt= false)
        {
            var curUser = sess.GetUserInfo(HttpContext);
            if (curUser != null)
            {
                UserInfo info = new UserInfo("DefaultSessionForNotLoginUsers", "", "");
                curUser = sess.SetUserInfo(info, HttpContext) ? sess.GetUserInfo(HttpContext) : curUser;
                var filters = filt ? "(ContentTypeId =" + (int)ContentTypeEnum.Example + ")" : "";
                curUser.Token = await ApiClientFactory.Instance.RefeshToken(curUser);

                sess.SetUserInfo(curUser, HttpContext);

                var returns = await ApiClientFactory.Instance.GetListLessonContents(filters, curUser.Token);
                return Json(returns);
            }
            return BadRequest("Request error");
        }

        [HttpPost]
        public async Task<IActionResult> AddEditLessonContentsMethod([FromQuery]string method, [FromBody] LessonContents obj)
        {
            if (ModelState.IsValid)
            {
                var curUser = sess.GetUserInfo(HttpContext);

                if (curUser != null)
                {
                    curUser.Token = await ApiClientFactory.Instance.RefeshToken(curUser);

                    sess.SetUserInfo(curUser, HttpContext);
                    var result = new Message<DataResults<LessonContents>>();
                    if (method == "edit")
                        result = await ApiClientFactory.Instance.UpdateLessonContent(obj, curUser.Token);
                    else if (method == "insert")
                        result = await ApiClientFactory.Instance.InsertLessonContent(obj, curUser.Token);

                    return Json(result);
                }                
            }
            return BadRequest("Request error");
        } 
        public async Task<IActionResult> DeleteLessonContent(int id =-1)
        {

            if (ModelState.IsValid)
            {
                var curUser = sess.GetUserInfo(HttpContext);

                if (curUser != null)
                {
                    curUser.Token = await ApiClientFactory.Instance.RefeshToken(curUser);

                    sess.SetUserInfo(curUser, HttpContext);
                    var result = new DataResults<int>();
                    if (id != -1)
                    {
                        result = await ApiClientFactory.Instance.DeleteLessonContent(id, curUser.Token);
                        return Json(result);
                    }
                }                           
            }
            return BadRequest("Request error");
        }
    }    
}

Source/w3schools_WEB/Controllers/LessonController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using w3schools_API.Models;
using w3schools_WEB.ApiCaller;
using w3schools_WEB.Helpers;
using w3schools_WEB.Models;

namespace w3schools_WEB.Controllers
{
    public class LessonController : Controller
    {
        private readonly Session sess;
        public LessonController(IOptionsSnapshot<ApiUrl> app)
        {
            ApplicationSettings.WebApiUrl = app.Value.WebApiBaseUrl;
            sess = new Session();
        }
        public IActionResult Index()
        {
            var curUser = sess.GetUserInfo(HttpContext);
            if (curUser.Role == "Administrator")
                return View();
            else if (!String.IsNullOrEmpty(curUser.Email))
                return RedirectToAction("Index", "Home");
            else
                return RedirectToAction("Login", "Auth");
        }
        [HttpGet]
        public async Task<IActionResult> GetListLesson()
        {            
            var curUser= sess.GetUserInfo(HttpContext);
            if (curUser != null)
            {
                UserInfo info = new UserInfo("User", "", "");
                curUser = sess.SetUserInfo(info, HttpContext) ? sess.GetUserInfo(HttpContext) : curUser;
                curUser.Token = await ApiClientFactory.Instance.RefeshToken(curUser);

                sess.SetUserInfo(curUser, HttpContext);

                var returns = await ApiClientFactory.Instance.getListLesson(curUser.Token);
                return Json(returns);
            }
            return BadRequest();
        }
        [HttpPost]
        public async Task<IActionResult> UpdateBatchLesson([FromBody]IEnumerable<UpdateBatchData<Lessons>> data)
        {
            var curUser = sess.GetUserInfo(HttpContext);

            if (curUser != null)
            {               
                curUser.Token = await ApiClientFactory.Instance.RefeshToken(curUser);

                sess.SetUserInfo(curUser, HttpContext);
                var result = await ApiClientFactory.Instance.updateBatchLesson(data, curUser.UserName, curUser.Token);
                return Json(result);
            }
            return BadRequest("Request error");
        }
    }
}

Source/w3schools_WEB/Views/LessonContents/Index.cshtml
@{
    Layout = "Admin_Layout";
    ViewData["Title"] = "Lesson Contents";
}
<div class="page-content">
    <div class="p-2">
        <div class="float-right">
            <button id="btnAddNew" type="button" class="btn btn-info"><i class="mr-2 fa fa-plus"></i>Add</button>  
        </div>
        <div class="clearfix"></div>
    </div>

    <div class="text-center grid-ctn">
        <div id="listData"></div>
    </div>
</div>

<script>
    var data = [];

    const listLesson = new DevExpress.data.CustomStore({
        key: "lessonId",
        loadMode:"raw",
        load: function () {
            var d = $.Deferred();
            $.ajax({
                "async": true,
                "crossDomain": true,
                "url": "@Url.Action("GetListLesson", "Lesson")",
                "headers": {
                    "Content-Type": "application/json",
                    "cache-control": "no-cache"
                },
                "method": "GET"
            }).done(function (result) {
                d.resolve(result);
            }).fail(function (xhr) {
                console.log("failed");
            });
            return d.promise();
        }
    });

    const listContentType = new DevExpress.data.CustomStore({
        key: "contentTypeId",
        loadMode:"raw",
        load: function () {
            var d = $.Deferred();
            $.ajax({
                "async": true,
                "crossDomain": true,
                "url": "@Url.Action("GetListContentType", "ContentType")",
                "headers": {
                    "Content-Type": "application/json",
                    "cache-control": "no-cache"
                },
                "method": "GET"
            }).done(function (result) {
                d.resolve(result);
            }).fail(function (xhr) {
                console.log("failed");
            });
            return d.promise();
        }
    });

    var store = new DevExpress.data.CustomStore({
        key: ["lessonContentId"],
        load: function () {
            var d = $.Deferred();
                $.ajax({
                    "async": true,
                    "crossDomain": true,
                    "url": "@Url.Action("GetListLessContent", "LessonContents")",
                    "headers": {
                        "Content-Type": "application/json",
                        "cache-control": "no-cache"
                    },
                    "method": "GET"
                }).done(function (result) {
                    data = result;
                    d.resolve(result);
                }).fail(function (xhr) {
                    console.log("failed");
                });

            return d.promise();
        }
    });

    var grid = $("#listData").dxDataGrid({
        dataSource: store,
        paging: {
            pageSize: 5
        },
        pager: {
            showPageSizeSelector: true,
            allowedPageSizes: [5, 10, 20, 50],
            showNavigationButtons: true,
            showInfo: true
        },
        remoteOperations: false,
        selection: {
            mode: 'simple'
        },
        editing: {
            mode: "row",
            useIcons: true,
            allowAdding: true,
            allowUpdating: true,
            allowDeleting: true
        },
        repaintChangesOnly: true,
        allowColumnReordering: true,
        rowAlternationEnabled: true,
        showBorders: true,
        forceIsoDateParsing: true,
        headerFilter: {
            visible: true
        },
        filterRow: { visible: true },
        dateSerializationFormat: "yyyy-MM-ddTHH:mm:ssx",
        allowColumnResizing: true,
        columnAutoWidth: true,
        //columnHidingEnabled: true,
        onToolbarPreparing: function (e) {
            e.toolbarOptions.items[0].visible = false;
            }, masterDetail: {
                enabled: true,
                template(container, options) {
                    const curr = options.data;

                    $('<div>')
                        .html(curr.content)
                        .appendTo(container);
                }
            },
        columns: [
            {
                caption: "Lesson Content Id",
                dataField: "lessonContentId",
                allowEditing: false,
                width: "15%",
                visible: false
            },
            {
                caption: "Lesson Content Title",
                dataField: "contentTitle",
                width: "15%",
                validationRules: [{
                    type: "required",
                    message: "Lesson Content Title is required"
                }]
            },
            {
                caption: "Lesson ContentType",
                dataField: "contentTypeId",
                width: "15%",
                validationRules: [{
                    type: "required",
                    message: "LessonContentType is required"
                }], lookup: {
                    dataSource: listContentType,
                    valueExpr: 'contentTypeId',
                    displayExpr: 'contentTypeName',
                },
            },
            {
                caption: "Lesson",
                dataField: "lessonId",
                width: "15%",
                allowEditing: false,
                visible: true, validationRules: [{
                    type: "required",
                    message: "LessonName is required"
                }],
                lookup: {
                    dataSource: listLesson,
                    valueExpr: 'lessonId',
                    displayExpr: 'lessonName',
                },
            },
            {
                caption: "Content",
                dataField: "content",
                width: "40%",
                validationRules: [{
                    type: "required",
                    message: "Content Type is required"
                }],
            },
            {
                caption: "ContentOrder",
                dataField: "contentOrder",
                width: "10%",
                validationRules: [{
                    type: "required",
                    message: "ContentOrder is required"
                }],
            },{
                type: "buttons",
                width: 110,
                buttons: [
                    {
                        hint: "Edit",
                        icon: "edit",
                        onClick: function(e) {
                            location.href = "@Url.Action("AddEditLessonContentsView", "LessonContents")?id=" + e.row.data.lessonContentId + "&method=edit";
                        }
                    },
                    {
                        hint: "Delete",
                        icon: "trash",
                        onClick: function (e) {
                            var result = DevExpress.ui.dialog.confirm("<i>Are you sure?</i>", "Confirm changes");
                            result.done(function (val) {
                                if (val) {
                                    $.ajax({
                                        "async": true,
                                        "crossDomain": true,
                                        "url": "@Url.Action("DeleteLessonContent","LessonContents")?id=" + e.row.data.lessonContentId,
                                        "headers": {
                                            "Content-Type": "application/json",
                                            "cache-control": "no-cache"
                                        },
                                        "method": "get"

                                    }).done(function (result) {
                                        if (result.status == 1) {
                                            DevExpress.ui.notify(result.message, "success", 2000);
                                            grid.refresh();
                                        }
                                        else
                                            DevExpress.ui.notify(result.message, "warning", 2000);
                                    }).fail(function (xhr) {
                                        DevExpress.ui.notify("Error!Not completed", "warning", 2000);
                                    });
                                }
                            });
                        }
                    }
                ]
            }
            ]
        }).dxDataGrid("instance");

    $("#btnAddNew").on("click", function () {
        location.href = "@Url.Action("AddEditLessonContentsView", "LessonContents")?method=insert&order=" + (data[data.length - 1].contentOrder + 1);
    });

    $(function () {
        $(".breadcrumb").children().last().find("span").text("Lesson Content");
    })

</script>