Source/w3schools_WEB/Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using w3schools_API.Models;
using w3schools_WEB.ApiCaller;
using w3schools_WEB.Helpers;

namespace w3schools_WEB.Controllers
{
    public class AuthController : Controller
    {
        public IActionResult Login()
        {
            return View();
        }
        public IActionResult Signup()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> LoginMethod(Users data)
        {
            if (data != null)
            {
                var rt = new DataResults<UserInfo>();                
                if (String.IsNullOrEmpty(data.Email))
                {
                    rt.Message += "Email is required!";
                }
                else
                {
                    data.Email = data.Email.ToLower().Trim();
                    string emailRegex = @"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}" +
                                        @"\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\" +
                                        @".)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$";
                    Regex re = new Regex(emailRegex);
                    if (!re.IsMatch(data.Email))                    
                        rt.Message += "Email is not valid!";                    
                }
                if (String.IsNullOrEmpty(data.PassWord))
                {
                    rt.Message += "Password is required!";
                }               
                if (!String.IsNullOrEmpty(rt.Message))
                    return Ok(rt);
            }

            var rs = await ApiClientFactory.Instance.checkLogin(data);

            if (rs.Status == 1)
            {
                var session = HttpContext.Session;

                var obj = new UserInfo();
                obj = rs.Data;

                var memoryCache = new Session();
                memoryCache.AddSection(session, obj);
            }
            return Ok(rs);
        }        
        public  IActionResult Signout()
        {
            var sess = new Session();
            var curUser = sess.GetUserInfo(HttpContext);

            if (curUser != null)
            {                
                var session = HttpContext.Session;
                sess.ClearSection(session);                
            }
            return View("Login");
        }

        [HttpGet]
        public IActionResult SignoutWithAjax()
        {
            var rt = new DataResults<int>();
            var sess = new Session();
            var curUser = sess.GetUserInfo(HttpContext);

            if (curUser != null)
            {
                var session = HttpContext.Session;
                sess.ClearSection(session);
                rt.Message = "Successfuly";
                rt.Status = 1;
            }
            else
            {
                rt.Message = "Failed";
                rt.Status = -1;
            }
            return Ok(rt);
        }

        [HttpPost]
        public async Task<IActionResult> SignupMethod(SingupModel data)
        {
            if (data != null)
            {
                var rt = new DataResults<UserInfo>();
                if (String.IsNullOrEmpty(data.UserName))
                {
                    rt.Message = "Username is required!";
                }
                if (String.IsNullOrEmpty(data.Email))
                {
                    rt.Message += "Email is required!";
                }
                else
                {
                    data.Email = data.Email.ToLower().Trim();
                    string emailRegex = @"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}" +
                                        @"\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\" +
                                        @".)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$";
                    Regex re = new Regex(emailRegex);
                    if (!re.IsMatch(data.Email))
                    {
                        rt.Message += "Email is not valid!";
                    }
                }
                if(String.IsNullOrEmpty(data.PassWord) || String.IsNullOrEmpty(data.RePassWord))
                {
                    rt.Message += "Password and Re-enter Password is required!";
                }
                else if(data.PassWord != data.RePassWord) {
                    rt.Message += "Re-enter password is not match!";
                }
                else
                {
                    data.PassWord = data.PassWord.Trim();
                    var hasNumber = new Regex(@"[0-9]+");
                    var hasUpperChar = new Regex(@"[A-Z]+");
                    var hasMinimum8Chars = new Regex(@".{8,}");

                    var isValidated = hasNumber.IsMatch(data.PassWord) && hasUpperChar.IsMatch(data.PassWord) && hasMinimum8Chars.IsMatch(data.PassWord);
                    if (!isValidated)
                    {
                        rt.Message += "Password must contain numbers, uppercase letters and be at least 8 characters long!";
                    }
                }
                if (!String.IsNullOrEmpty(rt.Message))
                    return Ok(rt);
            }
            data.RoleId = 2;
            var rs = await ApiClientFactory.Instance.signup(data);

            if (rs.Status == 1)
            {
                var session = HttpContext.Session;

                var obj = new UserInfo();
                obj = rs.Data;

                var memoryCache = new Session();
                memoryCache.AddSection(session, obj);
            }
            return Ok(rs);
        }
    }
}

Source/w3schools_WEB/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using w3schools_API.Models;
using w3schools_WEB.ApiCaller;
using w3schools_WEB.Helpers;
using w3schools_WEB.Models;

namespace w3schools_WEB.Controllers
{
    public class HomeController : Controller
    {
        private readonly Session sess;
        public HomeController(IOptionsSnapshot<ApiUrl> app)
        {
            ApplicationSettings.WebApiUrl = app.Value.WebApiBaseUrl;
            sess = new Session();
        }
        public IActionResult Index()
        {
            var curUser = sess.GetUserInfo(HttpContext);
            ViewBag.Username = curUser.UserName;
            return View();                   
        }
        public async Task<IActionResult> RenderContents(int id = -1)
        {
            var curUser = sess.GetUserInfo(HttpContext);

            curUser.Token = await ApiClientFactory.Instance.RefeshToken(curUser);

            sess.SetUserInfo(curUser, HttpContext);

            string filters = null;
            if (id != -1)
            {
                //( ContentType = N'Video' ) 
                filters = "(LessonId =" + id + ")";
            }
            if (ModelState.IsValid)
            {
                var model = new List<LessonContents>();
                if (id != -1)
                {
                    model = await ApiClientFactory.Instance.GetListLessonContents(filters, "");
                }

                return Json(model);
            }
            return BadRequest("Request Error");
        }    
    }
}

Source/w3schools_WEB/Controllers/LessonCategoriesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using w3schools_API.Models;
using w3schools_WEB.ApiCaller;
using w3schools_WEB.Helpers;
using w3schools_WEB.Models;

namespace w3schools_WEB.Controllers
{
    public class LessonCategoriesController : Controller
    {
        private readonly Session sess;
        public LessonCategoriesController(IOptionsSnapshot<ApiUrl> app /*,IOptionsSnapshot<AuthenInfo> authen*/)
        {            
            ApplicationSettings.WebApiUrl = app.Value.WebApiBaseUrl;
            sess = new Session();
        }
        public IActionResult Index()
        {
            var curUser = sess.GetUserInfo(HttpContext);
            if (curUser.Role == "Administrator")
                return View();
            else if (!String.IsNullOrEmpty(curUser.Email))
                return RedirectToAction("Index", "Home");
            else return RedirectToAction("Login", "Auth");
        }
        [HttpGet]
        public async Task<IActionResult> GetListLessonCategories()
        {
            var curUser = sess.GetUserInfo(HttpContext);

            if (curUser != null)
            {
                UserInfo info = new UserInfo("DefaultSessionForNotLoginUsers", "", "");
                curUser = sess.SetUserInfo(info, HttpContext) ? sess.GetUserInfo(HttpContext) : curUser;
                curUser.Token = await ApiClientFactory.Instance.RefeshToken(curUser);

                sess.SetUserInfo(curUser, HttpContext);
                var returns = await ApiClientFactory.Instance.getListLessonCate(curUser.Token);
                return Json(returns);
            }
            return BadRequest("Request error");
        }
        [HttpPost]
        public async Task<IActionResult> UpdateBatchLessonCategories([FromBody] IEnumerable<UpdateBatchData<LessonCategories>> data)
        {
            var curUser = sess.GetUserInfo(HttpContext);

            if (curUser != null)
            {
                curUser.Token = await ApiClientFactory.Instance.RefeshToken(curUser);

                sess.SetUserInfo(curUser, HttpContext);
                var result = await ApiClientFactory.Instance.updateBatchLessonCate(data, curUser.UserName, curUser.Token);
                return Json(result);
            }
            return BadRequest("Request error");
        }

    }
}

Source/w3schools_WEB/Controllers/LessonController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using w3schools_API.Models;
using w3schools_WEB.ApiCaller;
using w3schools_WEB.Helpers;
using w3schools_WEB.Models;

namespace w3schools_WEB.Controllers
{
    public class LessonController : Controller
    {
        private readonly Session sess;
        public LessonController(IOptionsSnapshot<ApiUrl> app)
        {
            ApplicationSettings.WebApiUrl = app.Value.WebApiBaseUrl;
            sess = new Session();
        }
        public IActionResult Index()
        {
            var curUser = sess.GetUserInfo(HttpContext);
            if (curUser.Role == "Administrator")
                return View();
            else if (!String.IsNullOrEmpty(curUser.Email))
                return RedirectToAction("Index", "Home");
            else
                return RedirectToAction("Login", "Auth");
        }
        [HttpGet]
        public async Task<IActionResult> GetListLesson()
        {            
            var curUser= sess.GetUserInfo(HttpContext);
            if (curUser != null)
            {
                UserInfo info = new UserInfo("User", "", "");
                curUser = sess.SetUserInfo(info, HttpContext) ? sess.GetUserInfo(HttpContext) : curUser;
                curUser.Token = await ApiClientFactory.Instance.RefeshToken(curUser);

                sess.SetUserInfo(curUser, HttpContext);

                var returns = await ApiClientFactory.Instance.getListLesson(curUser.Token);
                return Json(returns);
            }
            return BadRequest();
        }
        [HttpPost]
        public async Task<IActionResult> UpdateBatchLesson([FromBody]IEnumerable<UpdateBatchData<Lessons>> data)
        {
            var curUser = sess.GetUserInfo(HttpContext);

            if (curUser != null)
            {               
                curUser.Token = await ApiClientFactory.Instance.RefeshToken(curUser);

                sess.SetUserInfo(curUser, HttpContext);
                var result = await ApiClientFactory.Instance.updateBatchLesson(data, curUser.UserName, curUser.Token);
                return Json(result);
            }
            return BadRequest("Request error");
        }
    }
}

Source/w3schools_WEB/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    var username = ViewBag.Username;

}
@using Newtonsoft.Json

<script>
    let curr;
    let listLesson = [];
    let listContent = [];
    let listCate = [];
    let name = @Html.Raw(JsonConvert.SerializeObject(username));
    function renderSibar() {
        $(".sidebar-list").empty();
        for (let i = 0; i < listCate.length; i++) {
            var listRender = listLesson.filter(x => x.lessonCateId == listCate[i].lessonCateId);
            $(".sidebar-list").append('<li class="sidebar-item"><h1 class="sidebar-link">' + listCate[i].lessonCateName + '</h1></li>');
            for (let i = 0; i < listRender.length;i++) {
                $(".sidebar-list").append('<li class="sidebar-item"><a href="#" onclick="return getContent(' + listRender[i].lessonId + ')" class="sidebar-link" id="' + listRender[i].lessonId+'">' + listRender[i].lessonName + '</a></li>');
            }
        }
        return true;
    }

    function getContent(id) {
        curr = id;
        //add active class
        if ($(".sidebar-list").find("li.active").length > 0)
            $(".sidebar-list").find("li.active").removeClass("active");
        /*let index = listLesson.findIndex(x => x.lessonId == id);*/
        /*if (typeof $(".sidebar-list").children()[index].classList !== 'undefine')*/
        $(".sidebar-list").find("a#" + id).parent()[0].classList.add("active");
        $.ajax({
            "async": true,
            "crossDomain": true,
            "url": "@Url.Action("RenderContents", "Home")?id="+id,
            "headers": {
                "Content-Type": "application/json",
                "cache-control": "no-cache"
            },
            "method": "GET"
        }).done(function (result) {
             renderContent(result,id);
        }).fail(function (xhr) {
            console.log("get contents failed");
        });
        

        return false;
    }

    function getListLesson() {
        $.ajax({
            "async": true,
            "crossDomain": true,
            "url": "@Url.Action("GetListLesson", "Lesson")",
            "headers": {
                "Content-Type": "application/json",
                "cache-control": "no-cache"
            },
            "method": "GET"
        }).done(function (result) {
            listLesson = result;
            renderSibar();
            getContent(listLesson[0].lessonId);
        }).fail(function (xhr) {
            console.log("get lesson list failed");
        });
    }
    function getListCate() {
        $.ajax({
            "async": false,
            "crossDomain": true,
            "url": "@Url.Action("GetListLessonCategories", "LessonCategories")",
            "headers": {
                "Content-Type": "application/json",
                "cache-control": "no-cache"
            },
            "method": "GET"
        }).done(function (result) {
            listCate = result;

        }).fail(function (xhr) {
            console.log("get lesson categories failed");
        });
    }

    function renderContent(data, id) {
        var lessonName = (listLesson.filter(x => x.lessonId == id))[0].lessonName;
        $(".content-title").text(lessonName);
        var target = $("#content-body");
        target.empty();
        data.forEach(function (item, index) {
            var title = item.contentTitle ? item.contentTitle : "";
            var html = '<div class="text-block">' +
                '<h2 class="text-title">' + title + '</h2>' + item.content + '</div>';

            target.append(html);

            if (item.content.indexOf("try-it-btn") != -1)
                target.last().find("a.try-it-btn").attr("href", "/Example/ExampleView?id=" + item.lessonContentId);
            if (target.html().length > 0) {
                if (index < data.length - 1)
                    target.append("<hr>");
            }
        })
    }
    function lessonTraversing(e, cateId) {

        if ($("#items").find("li>a.active").length > 0)
            $("#items").find("li>a.active").removeClass("active");
        /*let index = listLesson.findIndex(x => x.lessonId == id);*/
        /*if (typeof $(".sidebar-list").children()[index].classList !== 'undefine')*/
        e[0].classList.add("active")
        if ((listCate.filter(x => x.lessonCateId === cateId)).length > 0) {
            let listLessons = listLesson.filter(x => x.lessonCateId === cateId);
            if (listLessons.length > 0)
                getContent(listLessons[0].lessonId);
        }
    }
    function prevOrNext(type){
        let currIndex = listLesson.findIndex(x => x.lessonId == curr);
        let index = type === 0 ? (currIndex > 0 ? currIndex - 1 : 0) : (type === 1 ? currIndex === listLesson.length - 1 ? currIndex : currIndex + 1 : 0);
        getContent(listLesson[index].lessonId);
    }
    $(".btn-next").on("click", function (e) {
        e.preventDefault();
        prevOrNext(1);
    });
    $(".btn-prev").on("click", function (e) {
        e.preventDefault();
        prevOrNext(0);
    });
    function login() {
        if (name) {
            $("#acc").empty().html('<ul class="navbar-nav ml-auto mr-3">' +
                '<!-- User info -->' +
                '<li class="nav-item dropdown">' +
                '<a class="nav-link" data-toggle="dropdown" href="#" style="font-size:xx-large">' +
                '<i class="fas fa-user-circle" ></i>' +
                '<span id="username">' + name + '</span>' +
                '</a>' +
                '<div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">' +
                '<a href="#" onclick="return logout()" class="dropdown-item" id="signout">' +
                '<i class="fas fa-sign-out-alt mt-2 mr-2"></i>Sign out' +
                '</a>' +
                '@*<div class="dropdown-divider"></div>*@' +
                '</div>' +
                '</li>' +
                '</ul>');
        }
    }
    function logout() {
        $.ajax({
            "async": true,
            "crossDomain": true,
            "url": "@Url.Action("SignoutWithAjax", "Auth")",
            "headers": {
                "Content-Type": "application/json",
                "cache-control": "no-cache"
            },
            "method": "GET"
        }).done(function (result) {
            if (result.status === 1) {
                $("#acc").empty().html('<div class="account">'+
                            '<div class="login">'+
                            '<a href="@Url.Action("Login","Auth")">Đăng Nhập</a>'+
                            '</div>'+
                            '<div class="register">'+
                            '<a href="@Url.Action("Signup","Auth")">Đăng Ký</a>'+
                            '</div>'+
                        '</div>');
            }

        }).fail(function (xhr) {
            console.log("Logout failed");
        });
    }
    $(function () {
        getListCate();
        getListLesson();
        login();
    })


</script>